const items = [
  {
    id: 1,
    title: 'Salada',
    category: 'Appetizers',
    price: 4,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/salda_aqfrft.jpg',
    desc: `Iceburg Lettuce, Tomato and Cheese `,
    model: 'Meal 1',
  },
  {
    id: 2,
    title: 'Camarão ao Alho',
    category: 'Appetizers',
    price: 14,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/camarao_alho_x5qijd.jpg',
    desc: `Shrimp Garlic Sauce`,
    model: 'Meal 2',
  },
  {
    id: 3,
    title: 'Picadinho Misto',
    category: 'Appetizers',
    price: 19,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/picanha_grelhada_ixrm9o.jpg',
    desc: `Pork Shrimp, Sausage and Calamari served with French Fries`,
    model: 'Cupcake',
  },
  {
    id: 4,
    title: 'Ameijoas à Bulhão Pato',
    category: 'Appetizers',
    price: 15,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/ameijoas_a_bulhao_pato_fxzdma.jpg',
    desc: `Littleneck Clams, Olive oil, Garlic, Cliantro and White Wine `,
    model: 'Chiken Plate',
  },
  {
    id: 5,
    title: 'Lulas Fritas',
    category: 'Appetizers',
    price: 15,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/lulas_fritas_f7fskm.jpg',
    desc: `Fried Calamari wtih Marinara Sauce `,
    model: 'Meatballs Plate',
  },
  {
    id: 6,
    title: 'Chouriço',
    category: 'Appetizers',
    price: 14,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/chourico_wjvgr9.jpg',
    desc: `Homemade Sausage Grilled in Portuguese Grappa`,
    model: 'Salmon Tartine',
  },
  {
    id: 7,
    title: 'Frango à Passarinho',
    category: 'Appetizers',
    price: 11,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/frango_a_passarinho_hb5jjy.jpg',
    desc: `Fried Chicken on the Bone`,
    model: 'Wood Board Rib',
  },
  {
    id: 8,
    title: 'Chicken Fingers',
    category: 'Appetizers',
    price: 11,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/chicken_fingers_zisfkt.jpg',
    desc: `Served with French Fries and Honey Mustard `,
    model: 'Joia Ribs',
  },
  {
    id: 9,
    title: 'Mozzarella Sticks',
    category: 'Appetizers',
    price: 10,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/mozzarella_sticks_v3hsfx.jpg',
    desc: `Served with Homemade Tomato Sauce`,
    model: 'Meal 1',
  },
  {
    id: 10,
    title: 'Mineirão',
    category: 'Appetizers',
    price: 23,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/mineirao_mwzp2a.jpg',
    desc: `Codfish Cakes, Shrimp Puffs, Fried Pork Belly, Fried Chicken on the bone and Yucca Fries`,
    model: 'Meal 1',
  },
  {
    id: 11,
    title: 'Picadindo Vaca com Cebola',
    category: 'Appetizers',
    price: 20,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/pcadinho_vaca_com_cebola_mgsr5z.jpg',
    desc: `Beef Cubes with French Fries and Sautéed Onions`,
    model: 'Meal 1',
  },
  {
    id: 12,
    title: 'Picadinho de Alcatra com Mandioca',
    category: 'Appetizers',
    price: 22,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/picadinho_de_alcatra_com_mandioca_i7tsuq.png',
    desc: `Top Rump Cubes, Melted Cheese and Yucca Fries`,
    model: 'Meal 1',
  },
  {
    id: 13,
    title: 'Rissois De Camarão ',
    category: 'Appetizers',
    price: 13.5,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/rissois_de_camarao_yoyn4f.jpg',
    desc: `Shrimp Puffs`,
    model: 'Meal 1',
  },
  {
    id: 14,
    title: 'Bolinhos de Bacalhau',
    category: 'Appetizers',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/bolinhos_de_bacalhau_lgmnoh.webp',
    desc: `Codfish Cakes `,
    model: 'Meal 1',
  },
  {
    id: 15,
    title: 'Misto de Linquiça',
    category: 'Appetizers',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/misto_de_linguica_yykrqy.jpg',
    desc: `Linquiça Calabresa e de Frango com Mozarella, Mandioca frita, Farafa e Vinagrete`,
    model: 'Meal 1',
  },
  {
    id: 16,
    title: 'Dourada Frita ou Grelhada',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/dourada_frita_ou_grelhada_d0agff.jpg',
    desc: `Whole Orata Grilled or Fried, Boiled Potatoes, Vegetables`,
    model: 'Meal 1',
  },
  {
    id: 17,
    title: 'Green or Red Mariscada',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/green_or_red_mariscada_gudrcl.jpg',
    desc: `Mixed Shelfish in Parsley in White Wine or Tomato Sauce`,
    model: 'Meal 1',
  },
  {
    id: 18,
    title: 'Paelha Marinera or Valenciana',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/paelha_marinera_or_valencia_qxp8xw.webp',
    desc: `Mixed Shelfish in Rice, Valenciana served with Seafood and Meat`,
    model: 'Meal 1',
  },
  {
    id: 19,
    title: 'Arroz de Camarão',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647912/arroz_de_camarao_gnwjfv.jpg',
    desc: `Shrimp in Saffron Rice`,
    model: 'Meal 1',
  },
  {
    id: 20,
    title: 'Salmao Grelhado',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/salmao_grelhado_nnzxxf.webp',
    desc: `Broiled Salmon served with Boiled Potatoes and Vegetables`,
    model: 'Meal 1',
  },
  {
    id: 21,
    title: 'Salmão Pôr do Sol',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/salmao_grelhado_nnzxxf.webp',
    desc: `Grilled Salmon with Shrimp, Boiled Potatoes and Vegetables`,
    model: 'Meal 1',
  },
  {
    id: 22,
    title: 'Gambas Mozambique',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/gambas_mozambique_lhztea.jpg',
    desc: `Colossal Prawns on the Shell, Garlic, White Wine, Spicy Touch`,
    model: 'Meal 1',
  },
  {
    id: 23,
    title: 'Bacalhau á Portuguesa',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/bacalhau_a_portuguesa_ne5jdj.jpg',
    desc: `Grilled Salted Cod Fish on the Bone, Boiled Potato and Vegetables`,
    model: 'Meal 1',
  },
  {
    id: 24,
    title: 'Arroz de Marisco',
    category: 'Seafood',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/arroz_de_marisco_o6esye.jpg',
    desc: `Mixed Shellfish in Rice`,
    model: 'Meal 1',
  },
  {
    id: 25,
    title: 'Grilled Filet Mignon Madeira',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/grilled_filet_mignon_madeira_qowjxf.webp',
    desc: `Grilled Filet Mignon, Madeira Wine Sauce, Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 26,
    title: 'Bife á Portuguesa',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/bife_a_portuguesa_e5wkkq.jpg',
    desc: `N.Y. Strip Steak w/Egg and slice of Ham,Rice,Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 27,
    title: 'Bife á Pôr do Sol',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/bife_a_por_do_sol_uovek6.jpg',
    desc: `N.Y. Strip Steak wtih Shrimp in Garlic Sauce, Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 28,
    title: 'Bife da Vazia',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/bife_de_vazia_uwpm2a.jpg',
    desc: `Grilled Strip Loin, Rice, Beans and French Fries `,
    model: 'Meal 1',
  },
  {
    id: 29,
    title: 'Alentejana',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/alentejana_nx2smo.jpg',
    desc: `Famous Pork Cubes and Fried Cubed Potatoes with Clams`,
    model: 'Meal 1',
  },
  {
    id: 30,
    title: 'Costela de Vaca no Churrasco',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/costela_de_vaca_no_churrasco_batynt.jpg',
    desc: `Grilled Short Ribs, Rice, Beans and French Friest`,
    model: 'Meal 1',
  },
  {
    id: 31,
    title: 'Bitoque',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/bitoque_tcjby1.jpg',
    desc: `Small Strip Loin, Garlic Sauce, Egg on top and Spanish Potatoes`,
    model: 'Meal 1',
  },
  {
    id: 32,
    title: 'Fraldinha à Brasileira',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/fraldinha_a_brasileira_mb7ny4.webp',
    desc: `Grilled Skirt Steak w/ 2 Eggs, Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 33,
    title: 'Picanha Grelhada',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/picanha_grelhada_ixrm9o.jpg',
    desc: `Grilled Top Sirloin Cap Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 34,
    title: 'T-Bone Grelhada ',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/tbone_grelhada_sveify.jpg',
    desc: `Grilled T-Bone Steak with Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 35,
    title: 'Costeletas de Porco Grelhadas',
    category: 'Meats',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/costeletas_de_porco_grelhadas_zek0mw.jpg',
    desc: `Grilled Pork Chops, Rice, Beans and French Fries`,
    model: 'Meal 1',
  },
  {
    id: 36,
    title: 'Salda',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/salda_aqfrft.jpg',
    desc: `Salada`,
    model: 'Meal 1',
  },
  {
    id: 37,
    title: 'Vegetables',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/vegetables_csl1o3.jpg',
    desc: `Vegetais`,
    model: 'Meal 1',
  },
  {
    id: 38,
    title: 'Rice',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/rice_ybfqx9.jpg',
    desc: `Arroz`,
    model: 'Meal 1',
  },
  {
    id: 39,
    title: 'Beans',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/beans_ackox8.jpg',
    desc: `Feijão`,
    model: 'Meal 1',
  },
  {
    id: 40,
    title: 'French Fries',
    category: 'Side Orders',
    price: 16.99,
    img: '.https://res.cloudinary.com/elpawl-llc/image/upload/v1671647912/french_fries_lc0e9p.jpg',
    desc: `Batatas Fritas`,
    model: 'Meal 1',
  },
  {
    id: 41,
    title: 'Spanish Potatoes',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/spanish_potatoes_rkwmgg.webp',
    desc: `Batata Espanhola`,
    model: 'Meal 1',
  },
  {
    id: 42,
    title: 'Boiled Potatoes',
    category: 'Side Orders',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/spanish_potatoes_rkwmgg.webp',
    desc: `Batata Cozida`,
    model: 'Meal 1',
  },
  {
    id: 43,
    title: 'Cheese Steak Sandwich',
    category: 'Sandwiches',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/spanish_potatoes_rkwmgg.webp',
    desc: `Grilled Sirloin Steak, Mozzarella Cheese and French Fries `,
    model: 'Meal 1',
  },
  {
    id: 44,
    title: 'Steak Sandwich',
    category: 'Sandwiches',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/steak_sandwich_dliw4l.jpg',
    desc: `Grilled Sirloin Steak with French Fries `,
    model: 'Meal 1',
  },
  {
    id: 45,
    title: 'Chicken Sandwich',
    category: 'Sandwiches',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/chicken_sandwich_aefwwn.webp',
    desc: `Grilled or Breaded Chicken Breast served with French Fries `,
    model: 'Meal 1',
  },
  {
    id: 46,
    title: 'Pork Sandwich',
    category: 'Sandwiches',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/pork_sandwich_hakua8.jpg',
    desc: `Portuguese famous "Febras". Pork Cutlets Fried or Grilled `,
    model: 'Meal 1',
  },
  {
    id: 47,
    title: 'Caipirinha',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/caipirinha_tcqfjt.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 48,
    title: 'Caipirinha w/ Passion Fruit',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/caipirinha_w_passion_fruit_honq0h.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 49,
    title: 'Caipirinha w/ Pineapple',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/caipirinha_pineapple_uzys4b.jpg',
    desc: `Mandioca`,
  },
  {
    id: 50,
    title: 'Large Sangria',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/large_sangria_zo3kyf.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 51,
    title: 'Small Sangria',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/small_sangria_bmaegg.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 52,
    title: 'Margarita',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/margarita_qdnc1i.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 53,
    title: 'Malibu Bay Breeze',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/long_island_iced_tea_tm7nqv.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 54,
    title: 'Long Island Iced Tea',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/long_island_iced_tea_tm7nqv.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 55,
    title: 'Caipi Vodka',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/caipivodka_tcttzy.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 56,
    title: 'Sex on the Beach',
    category: 'House Speciality Drinks',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/long_island_iced_tea_tm7nqv.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 57,
    title: 'Barefoot Cardonnay',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/barefoot_chardonnay_bxrvps.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 58,
    title: 'Yellow Tail Chardonnay',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/yellowtail_chardonnAY_h68z4e.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 59,
    title: 'Barefoot Moscato ',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647912/barefoot_moscato_b9pgk4.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 60,
    title: 'Yellow Tail Moscato ',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/yellowtail_moscato_e2om0f.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 61,
    title: 'Barefoot Pinot Grigio ',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/barefoot_pinot_grigio_ysqilm.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 62,
    title: 'Yellow Tail Pinot Grigio ',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/yellow_tail_pinot_noir_qbbfll.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 63,
    title: 'Zinfandel Gallo Family White Zinfandel',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/zinfandel_gallo_family_white_zinfandel_m0a65o.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 64,
    title: 'Zinfandel Gallo Family White Zinfandel',
    category: 'White Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/zinfandel_gallo_family_white_zinfandel_m0a65o.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 65,
    title: 'Monte Velho',
    category: 'Whites - Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/monte_velho_zdscun.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 66,
    title: 'Casal Garcia',
    category: 'Whites - Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/casal_garcia_gyayyu.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 67,
    title: 'Borba',
    category: 'Whites - Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/borba_uhsvrj.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 68,
    title: 'Muralhas',
    category: 'Whites - Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/muralhas_c2ksmb.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 69,
    title: 'Grao Vasco',
    category: 'Whites - Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/grao_vasco_oiygh7.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 70,
    title: 'Barefoot Merlot',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/barefoot_merlot_eqjktl.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 71,
    title: 'Yellow Tail Merlot',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/yellow_tail_merlot_tbxtmi.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 72,
    title: 'Barefoot Cabernet',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647913/barefoot_cabernet_krsa67.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 73,
    title: 'Yellow Tail Cabernet',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647914/yellow_tail_cabernet_hqdj42.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 74,
    title: 'Yellow Tail Pinot Noir',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647920/yellow_tail_pinot_noir_qbbfll.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 75,
    title: 'Lambrusco',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/lambrusco_hcmrlk.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 76,
    title: 'Silk & Spice',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/silk_spice_qj28nc.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 77,
    title: 'Duas Quintas',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647916/duas_quintas_fm0roa.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 78,
    title: 'Periquita',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/periquita_p63mbu.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 79,
    title: 'Periquita Reserva',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/periquita_reserva_jqmmpm.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 80,
    title: 'Malbec (Casillerodel Diablo)',
    category: 'Red Wines',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647912/malbec_casillero_del_diablo_ocv24d.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 81,
    title: 'Borba',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/borba_red_heaqlu.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 82,
    title: 'Monte Velho',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647919/monte_velho_zdscun.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 83,
    title: 'Eugenio de Almeida',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/eugenio_de_almeida_red_pakkob.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 84,
    title: 'Grao Vasco',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/grao_vasco_red_drpcq1.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 85,
    title: 'Monte Serra',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647915/monte_serra_nvykhh.png',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 86,
    title: 'JP',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647918/jp_xlfjph.webp',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
  {
    id: 87,
    title: 'Borba Reserva',
    category: 'Reds-Portugal',
    price: 16.99,
    img: 'https://res.cloudinary.com/elpawl-llc/image/upload/v1671647917/borba_reserva_y4v7lx.jpg',
    desc: `Mandioca`,
    model: 'Meal 1',
  },
]
export default items
